repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        files: ^(mealie_translate/|tests/|main\.py)
      # Run the formatter.
      - id: ruff-format
        files: ^(mealie_translate/|tests/|main\.py)

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.json"]

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest-unit
        entry: make pre-commit-test
        language: system
        pass_filenames: false
        always_run: true
